import { readFile, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
const root = new URL('../', import.meta.url);
const sources = ['solar-energy-flow-component/solar-energy-flow.js', 'src/solar-flow-card.js'];
const bundle = '// Solar Flow Card v3.0.0 — generated by node scripts/build.mjs\n' +
  (await Promise.all(sources.map(path => readFile(new URL(path, root), 'utf8')))).join('\n');
await writeFile(new URL('solar-flow-card.js', root), bundle);
await writeFile(new URL('solar-flow-card.js.gz', root), gzipSync(bundle));
